name:  "Terraform CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    chechov-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Run Checkov
              uses: bridgecrewio/checkov-action@master
              with:
                directory:
                soft_fail: true
                framework: terraform
    terraform-test:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout code
               uses: actions/checkout@v4

             - name: terraform download
               uses: hashicorp/setup-terraform@v3

             - name: terraform init
               run:  terrafom init
             - name: Terraform plan
               run:  terraform plan

